
save_predictions:
  _target_: goo.callbacks.save_predictions.SavePredictions
  metrics_calculate: ['accuracy', 'mean_class_accuracy']
  calculate_point: batch
  calculate_stages: ['train', 'val', 'test', 'predict']
