_target_: goo.datasets.base_csv_dataset.CSVDataModule
base_dir: '/media/nbloomfield/Question/phd-data/'
data_dir: 'CUB_200_2011/'
train_folder: 'CUB_200_2011/images/'
train_csv_file: 'cub-train.csv'
train_csv_image: 'imagepath'
train_csv_label: 'class'
train_image_ext: ''

val_folder: 'CUB_200_2011/images/'
val_csv_file: 'cub-test.csv'
val_csv_image: 'imagepath'
val_csv_label: 'class'
val_image_ext: ''
