_target_: goo.datasets.torchvision_lightning.TorchvisionDataModule
data_dir: datasets
split_style: 'trainval'
TorchvisionDataset:
  _target_: goo.datasets.torchvision.torchvision_vocdetection_2012seg.MyVOCSegmentation
  _partial_: True
