networks:
  student:
    _target_: goo.networks.proteus_dinov2.vit_tiny
    _partial_: true
    img_size: 224
    patch_size: 14
    init_values: 1.0
    ffn_layer: 'mlp'
    block_chunks: 0
    num_register_tokens: 0
    interpolate_antialias: False
    interpolate_offset: 0.1

  teacher:
    _target_: torch.hub.load
    _partial_: true
    repo_or_dir: 'facebookresearch/dinov2'
    model: 'dinov2_vits14_lc'
