# @package _global_
defaults:
  - /R: proteus
  - /model/networks: proteus_vit_s_t
  - /model/dataset: torchvision_cifar100
  - /model/dataset@model.dataset_override: imagenet
  - _self_

task_name: "CosPress_imagenet_dinov2_vits"

predict: False
delete_checkpoint: False

model:

  methods:
    _target_: goo.methods.self_supervised.proteus_vmfsne7_reversed.Proteus
    lambda_local: 1.0
    lambda_global: 1.0
    model_ema: False
    target_temperature_list: [0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.10]
    architecture: 'identity'
    target_mask: True
    sne_style: 'full'
    lambda_fea: 1.0
    lambda_token: 1.0
    metric: 'Cosine'
    freeze_heads_backwards: True
    conjoin_heads: True

  scheduler:
    scheduler:
      args:
        lr: 5.0e-4
        warmup_epochs: 5

  optimizer:
    optimizer:
      args:
        lr: 5.0e-4
        weight_decay: 0.05

  networks:
    networks:
      student:
        _target_: goo.networks.proteus_dinov2.vit_tiny
        _partial_: true
        img_size: 224
        patch_size: 14
        init_values: 1.0
        ffn_layer: 'mlp'
        block_chunks: 0
        num_register_tokens: 0
        interpolate_antialias: False
        interpolate_offset: 0.1

      teacher:
        _target_: torch.hub.load
        _partial_: true
        repo_or_dir: 'facebookresearch/dinov2'
        model: 'dinov2_vits14_lc'

  trainer:
    precision: '16-mixed'
    benchmark: True
    check_val_every_n_epoch: 10
    max_epochs: 300
    # gradient_clip_val: 0.1
    # gradient_clip_algorithm: "norm"
    # limit_train_batches: 50
    # limit_val_batches: 50
    # log_every_n_steps: 1
    # ============================================

  dataloaders:
    batch_size: 1024
    pin_memory: False
    val_collate_fn: null

  callbacks:
    learning_rate_monitor:
      log_weight_decay: True
    model_checkpoint:
      monitor: "val/forward_student_kNN_accuracy"
      mode: "max"

  custom_callbacks:
    save_knn_pred3:
      _target_: goo.callbacks.save_knn_pred.KNNPrediction
      backbone: 'forward_student'
      check_knn_every: 10
      nearest_neighbours: 200
      temperature: 0.1
      sample_frac: 0.2


  augmentations:
    aug_validation:
      _partial_: true
      _target_: goo.augmentations.center_crop.CenterCropAugment
      crop_size: 224
      resize: 256
      stretch: False
      normalize:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
    aug_predict:
      _partial_: true
      _target_: goo.augmentations.center_crop.CenterCropAugment
      crop_size: 224
      resize: 256
      stretch: False
      normalize:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]