# @package _global_
defaults:
  - /R: dinov2_linear_classifier
  - /model/networks: dinov2_vits_14_linear_classifier
  - /model/dataset: imagenette
  # - /model/dataset@model.dataset_override: imagenet
  - /model/dataset@model.dataset_override: torchvision_cifar100
  - _self_

task_name: "eval_knn"

train: False
test: True
predict: False

model:
  trainer:
    limit_train_batches: 1250
    max_epochs: 20
    use_distributed_sampler: False
    strategy: 'ddp_find_unused_parameters_true'

  networks:
    networks:
      backbone:
        _target_: goo.networks.dinov2_linear_classifier.ModelWithIntermediateLayers
        _partial_: true
        feature_model:
          _target_: goo.networks.load_module.LoadModule
          model_class: 
            # _target_: goo.methods.self_supervised.proteus.Proteus
            _target_: goo.methods.self_supervised.proteus_vmfsne7_reversed.Proteus
            _partial_: true
          # model_path: 'weights/proteus_vitt_vits.ckpt'
          model_path: 'weights/tintem_vitt_vits.ckpt'
          seed: -1
          module_name: 'student.backbone'
          module_target: 'backbone'
          disable_grad: True
        n_last_blocks: 1
        outputs: 'cls_tkn'
        no_inference: False
        inner_model: True

      discriminator:
        normalize: 'batchnorm'
  
  custom_callbacks:
    save_predictions:
      _target_: goo.callbacks.save_predictions.SavePredictions
      metrics_calculate: ['accuracy'] # , 'mean_class_accuracy', 'aucroc', 'average_precision'
      calculate_point: epoch
      calculate_stages: ['train', 'val', 'test']
      save_csv: False
    save_knn_pred:
      _target_: goo.callbacks.save_knn_pred.KNNPrediction
      backbone: 'backbone'
      check_knn_every: 10
      nearest_neighbours: 10
      temperature: 0.07


  optimizer:
    optimizer:
      weight_decay: 0.0
      momentum: 0.9

  dataloaders:
    batch_size: 1024
    pin_memory: False

  methods:
    batch_size: 1024
    learning_rates: [1e-5]
    avgpool: [False]
    n_last_blocks: [1]

  augmentations:
    aug_labelled:
      input_size: 224
    aug_validation:
      crop_size: 224
      resize: 256
    aug_predict:
      crop_size: 224
      resize: 256

