scheduler:
  _target_: goo.scheduler.timm_wrapper.timm_wrapper
  _partial_: true
  args: 
    sched: 'cosine'
    lr: 5.0e-4
    lr_noise: null
    lr_noise_pct: 0.67
    lr_noise_std: 1.0
    warmup_lr: 1.0e-6
    min_lr: 1.0e-5
    decay_epochs: 30
    warmup_epochs: 5
    cooldown_epochs: 10
    patience_epochs: 10
    decay_rate: 0.1
    seed: 0

scheduler_lightning:
  interval: epoch
