scheduler:
  _target_: goo.scheduler.dino_cosine_scheduler.CosineScheduler
  _partial_: true
  warmup_prop: [0.0, 0.0]
  warmup_value: [0.0, 0.0]
  base_value: [0.005, 0.4]
  final_value: [1e-6, 0.04]
  attribute: ['lr', 'weight_decay']
  T_max: 1

scheduler_lightning:
  interval: step
